### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'latest'

### ISSUE THREAD

**Issue by Write** [seleniumbase/SeleniumBase#1695]
```
Warning: chromedriver not found. Getting it now:

*** chromedriver version for download = 109.0.5414.74 (Latest)

Downloading chromedriver_linux64.zip from:
https://chromedriver.storage.googleapis.com/109.0.5414.74/chromedriver_linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver_linux64.zip ...
Unzip Complete!

The file [chromedriver] was saved to:
/usr/local/lib/python3.9/dist-packages/seleniumbase/drivers/chromedriver

Making [chromedriver 109.0.5414.74] executable ...
[chromedriver 109.0.5414.74] is now ready for use!

Traceback (most recent call last):
  File "/root/frigate/test.py", line 4, in <module>
    driver = Driver(headless=True, uc=True)
  File "/usr/local/lib/python3.9/dist-packages/seleniumbase/plugins/driver_manager.py", line 394, in Driver
    driver = browser_launcher.get_driver(
  File "/usr/local/lib/python3.9/dist-packages/seleniumbase/core/browser_launcher.py", line 1149, in get_driver
    return get_local_driver(
  File "/usr/local/lib/python3.9/dist-packages/seleniumbase/core/browser_launcher.py", line 2713, in get_local_driver
    and int(use_version) >= 72
ValueError: invalid literal for int() with base 10: 'latest'
```

```
╰─➤  lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

Also, I tried after that to manually download chromedriver 108 and put it in /usr/local/bin, so it's in my path, but still, deleting /usr/local/lib/python3.9/dist-packages/seleniumbase/drivers/chromedriver doesn't work as it redownload it evertime instead of using the chromedriver that is in my path.

**Comment by mdmintz** [comment]
I see the issue. There was a
``use_version.isnumeric`` instead of
``use_version.isnumeric()``.
I'll ship a fix shortly. Probably only happens in undetected-chromedriver mode when the driver manager can't detect the version, in which case it uses "latest" instead of a number.

**Comment by mdmintz** [comment]
Fixed in ``4.11.9`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.11.9

**Comment by Write** [comment]
Thanks a lot, that indeed fix the issue.

I still can't use uc mode, ps aux shows directly chrome as <defunct> when uc=True. 
Works great without headless. The command never times out, so I have no real idea what happens. If I use CTLR+C it just seems to be stuck over trying to connect to chrome. 
Should I post a new issue ?

**Comment by mdmintz** [comment]
@Write I'll need to know the version of Chrome that you have on your Linux machine, and the full PATH/NAME so that I can be certain that the driver manager is looking in the correct spot for it. Then I can fix it. Probably makes sense to open a separate ticket for this, but if you do, I need to know 1. The Version (eg. ``105``) 2. The PATH (eg. ``/usr/local/new_bin/``) and 3. The Name of the binary (eg. ``google-chrome``). With those three pieces of data, I can fix your second issue.

**Comment by mdmintz** [comment]
It's also possible that your second issue was resolved in ``4.12.1`` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.12.1
