### ISSUE TITLE
Intermittent error: "result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response"

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#2259]
Looks like there's a new intermittent error message appearing on Chrome 119:

```
E         selenium.common.exceptions.WebDriverException: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
E         (Session info: chrome=119.0.6045.123)
```

It's not specific to SeleniumBase. Regular Selenium users are being hit by it:
(https://stackoverflow.com/q/77428873/7058266 --> 9K views in 3 days):

<img width="1000" alt="Screenshot 2023-11-09 at 10 13 56 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/99737c27-d6f6-409c-afac-1e01a5b0a941">

However, SeleniumBase is still being impacted by it, intermittently:
(Had chromedriver `119.0.6045.105` and Chrome `119.0.6045.123`)

<img width="1420" alt="Screenshot 2023-11-09 at 10 19 23 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/cd6a7304-e54f-41a1-b93d-897fdb35c442">

There was an issue opened about it in the main Selenium org: https://github.com/SeleniumHQ/selenium/issues/13081
(However, it appears that the issue was closed, and that no work will be done on it.)

As Batman would say: **"I'll look into it."**

<img width="500" alt="Screenshot 2023-11-09 at 10 51 50 AM" src="https://github.com/seleniumbase/SeleniumBase/assets/6788579/b8085b35-bd60-4728-aca5-fa8d609a3476">

**Comment by Marsango** [comment]
Same problem here.

**Comment by mdmintz** [comment]
Resolved in `4.21.1` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.21.1

If you ran into this issue when using `self.open(url)` / `sb.open(url)`, then hopefully you won't run into this issue anymore. The fix involved automatically spinning up a new browser (since the previous one crashed) before attempting to open the URL again.

**Comment by ft1-1** [comment]
Still having this issue with 4.21.1 where the page loads then crashes.

Downloading chromedriver-win64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
An error occurred: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.124)

**Comment by mdmintz** [comment]
@ft1-1 I would need to see the full stack trace in order to debug.

**Comment by ft1-1** [comment]
Sorry, here you go:

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
An error occurred: Message: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=119.0.6045.124)
Stacktrace:
        GetHandleVerifier [0x00007FF632BB8EF2+54786]
        (No symbol) [0x00007FF632B25612]
        (No symbol) [0x00007FF6329DA64B]
        (No symbol) [0x00007FF6329DEEC1]
        (No symbol) [0x00007FF6329E14AA]
        (No symbol) [0x00007FF632A55394]
        (No symbol) [0x00007FF632A3BE6A]
        (No symbol) [0x00007FF632A54D02]
        (No symbol) [0x00007FF632A3BC43]
        (No symbol) [0x00007FF632A10941]
        (No symbol) [0x00007FF632A11B84]
        GetHandleVerifier [0x00007FF632F07F52+3524194]
        GetHandleVerifier [0x00007FF632F5D800+3874576]
        GetHandleVerifier [0x00007FF632F55D7F+3843215]
        GetHandleVerifier [0x00007FF632C55086+694166]
        (No symbol) [0x00007FF632B30A88]
        (No symbol) [0x00007FF632B2CA94]
        (No symbol) [0x00007FF632B2CBC2]
        (No symbol) [0x00007FF632B1CC83]
        BaseThreadInitThunk [0x00007FFF6C2E7344+20]
        RtlUserThreadStart [0x00007FFF6C5E26B1+33]

**Comment by mdmintz** [comment]
@ft1-1 The line / lines of code of SeleniumBase where the stack trace occurred is what I need to know to fix this.

**Comment by ft1-1** [comment]
Sorry, not sure exactly what line it crashes on. It is basically right after opening the url:

from seleniumbase import Driver
import time
from datetime import datetime
import config

DIR = '/project/profile1'

driver = Driver(uc=True, user_data_dir=DIR)

def login(driver):
    driver.get(config.LOGIN_URL)
    time.sleep(5)

**Comment by mdmintz** [comment]
@ft1-1 It might be due to the reason I already answered in https://www.youtube.com/watch?v=5dMFI3e85ig at 20:44 and again at 21:46. You may be trying to mix a user-data-dir from non-UC-Mode Chrome with UC Mode Chrome. That's what the video referred to as "Crossing the Streams". Make sure that user-data-dir gets created by UC Mode and is only used by UC Mode. That also means that you can only use the default profile of a user-data-dir. For each unique profile that you need, use another new user-data-dir.
