### ISSUE TITLE
Suddenly unable to bypass CloudFlare challenge (Ubuntu Server)

### ISSUE THREAD

**Issue by Jobine23** [seleniumbase/SeleniumBase#2842]
Hello, overnight my instances of seleniumbase became unable to bypass the CloudFlare challenge ( which uses CloudFlare turnstile ).

I was using an older version of SB so I updated to latest ( 4.27.4 ), and it is still not passing the challenge.

![cloudflare_chal](https://github.com/seleniumbase/SeleniumBase/assets/30392487/4dd970c4-757d-4ab7-a5c8-6b09a2c52611)

I am using your demo code for clicking on the CloudFlare turnstile captcha:

```
from seleniumbase import SB

def open_the_turnstile_page(sb):
    url = "https://wildbet.gg/"
    sb.driver.uc_open_with_reconnect(url, reconnect_time=5)

def click_turnstile_and_verify(sb):
    sb.switch_to_frame("iframe")
    sb.driver.uc_click("span")
    sb.assert_element("img#captcha-success", timeout=3)

with SB(uc=True, test=True) as sb:
    open_the_turnstile_page(sb)
    try:
        click_turnstile_and_verify(sb)
    except Exception:
        open_the_turnstile_page(sb)
        click_turnstile_and_verify(sb)
    sb.set_messenger_theme(location="top_left")
    sb.post_message("SeleniumBase wasn't detected", duration=3)
```

if I instead use:
`sb.driver.uc_open_with_reconnect(url, reconnect_time=9999)`

and click manually, it works. This means they are detecting something ?

I also tried adding `reconnect_time=5` on uc_click and it did not help.

I'm a big fan of your project and I've been using it for some time :)

**Comment by mdmintz** [comment]
Just tested on `seleniumbase` `4.27.5`, and the following script is working for me:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://wildbet.gg/"
    sb.driver.uc_open_with_reconnect(url, 10)
```

If you're still getting blocked, it might be that you exceeded a rate limit for your IP Address.

**Comment by Jobine23** [comment]
Thank you for your reply. I am not sure to understand. Why would it be related to any kind of ratelimiting if I can edit the code to disconnect permanently then click myself so that it goes through ? The only difference between error and success is that I click manually.

**Comment by mdmintz** [comment]
You can try that if it helps. When I ran the UC Mode script for that page, the script never had to click anything to bypass the CAPTCHA.

**Comment by JimKarvo** [comment]
We have the same problem at headless systems -ubuntu server-. 2 different servers, the ip is rotated - whitelisted

**Comment by vmolostvov** [comment]
@mdmintz same problem here on linux vds (ubuntu without gpu), seleniumbase became unable to bypass the CloudFlare challenge. Using latest sb version. On local macos and windows keep working without any problem.
![telegram-cloud-photo-size-2-5416106455389561099-w](https://github.com/seleniumbase/SeleniumBase/assets/67498478/bec2a762-ff60-45c0-8807-9a869a381300)

**Comment by vmolostvov** [comment]
> We have the same problem at headless systems -ubuntu server-. 2 different servers, the ip is rotated - whitelisted

do you find any solution sir?

**Comment by JimKarvo** [comment]
> > We have the same problem at headless systems -ubuntu server-. 2 different servers, the ip is rotated - whitelisted
> 
> did you find any solution sir?

Not yet, waiting if @mdmintz has any suggestions

**Comment by mdmintz** [comment]
OK, sounds like something has changed because there are a few different people showing up here. And this also sounds like this is specific to Linux because everything is working normally on macOS and Windows for me.

I'm still going to need more details to assist:
* What version of Linux are you using?
* What version of SeleniumBase are you using?
* Does it still work on an earlier version of SeleniumBase, and if so, what's the highest version that it still works on?
* Which Chrome/Version is installed on your machine? (Note that `google-chrome` and `chromium` are different!)
* Does it work if you use `xvfb=True` (virtual display) with `headed=True` (override default headless mode on Linux)?

This will help me figure out what's going on. Everything is working normally for me on macOS and Windows.

**Comment by EnmeiRyuuDev** [comment]
Hello @mdmintz ,
I also had the issue yesterday at all my VMs,
Not only Linux (Ubuntu 22.04, Debian 11), but also in a Windows Server 2022,
It works perfectly only in my personal laptop having Windows 11 Home,
Basically:
At VMs:
- it never passes without displaying the CF checkbox challenge
- uc_click seems to be detected, and it never recovers
- on the same SB browser, when clicking manually instead of letting SB clicks, it works pretty quick after the manual click
- tried with or without proxy, the same results
- versions:
google-chrome version 125.0.6422.142 under Windows Server,  google-chrome version  124.0.6367.118 under Ubuntu 22.04, google-chrome version 122.0.6261.111 under Debian 11.
I also tried going in SeleniumBase version as old as v4.23.0, v4.20.8, but it didn't help (same blockage behavior).

At my personal laptop (Windows 11):
- most of the time, it passes without having to click anything
- when it has to click, it passes as well
- tried with or without proxy (same proxy that's used for the VMs) -> always working fine
- versions:
google-chrome version 125.0.6422.142

It looks like Cloudflare is able to tell if I'm using a VM somehow, but yet, it works when clicking manually..
I can say it can be quickly reproduced on any Google Compute Engine VM.

I hope my description is helpful,
And thanks for the great project ^^

**Comment by EnmeiRyuuDev** [comment]
@mdmintz 
To complete answering your questions:
- Used SeleniumBase version, the latest: v4.27.5
- On Linux instances, I tried: xvfb=True, with headed=True, but it didn't help.

**Comment by mdmintz** [comment]
Looks like we've narrowed it down to an environment issue.
Try this script, and let me know which environments it works on and which it fails on:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://visa.vfsglobal.com/fra/en/hrv/login"
    sb.driver.uc_open_with_reconnect(url, 6)
    sb.switch_to_frame("iframe")
    sb.driver.uc_click("span")
    breakpoint()
```

Worked for me on my Mac, but sounds like it won't work on some Linux server environments.

**Comment by SaberTawfiq** [comment]
https://github.com/seleniumbase/SeleniumBase/assets/152691314/a369e2a1-5bc4-418c-9ccf-4d88f7106b54

**Comment by JimKarvo** [comment]
@mdmintz  For Ubuntu 20.04.6 LTS - server edtition, the script you provided not even clicks at span for some reason

**Comment by mdmintz** [comment]
OK, getting somewhere. Seeing differences on Mac vs Windows. Two videos below.

----

On a Mac, script worked as is. (Adjust `reconnect_time` based on your Internet connection speed.):

https://github.com/seleniumbase/SeleniumBase/assets/6788579/cb9eebdc-7b1a-4079-86fb-01abca6f4bc7

----

On Windows, had to add `incognito=True` in order for the script to work:

https://github.com/seleniumbase/SeleniumBase/assets/6788579/487fdd0e-aa27-49a4-883e-14b4842bcb1d

----

Did adding `incognito=True` to your `SB()` call help any of you?

If so, add it to all your scripts.
If not, let me know details, such as "worked locally on Windows, but not on Ubuntu Server", for example.
In order for me to fix this properly, I need to know exactly what conditions & environments are bad vs good.

**Comment by OpsecGuy** [comment]
```
"environment": {
    "implementation_name": "cpython",
    "implementation_version": "3.12.1",
    "os_name": "nt",
    "platform_machine": "AMD64",
    "platform_release": "10",
    "platform_system": "Windows",
    "platform_version": "10.0.19045",
    "python_full_version": "3.12.1",
    "platform_python_implementation": "CPython",
    "python_version": "3.12",
    "sys_platform": "win32"
  }
```
```
Name: seleniumbase
Version: 4.27.5
```

Driver object:
```
def create(self):
        return Driver(
            browser='chrome',
            incognito=True,
            dark_mode=True,
            headless2=self.summary.headless,
            proxy=self.proxy_addr,
            uc=True,
            uc_subprocess=True,
            # extension_dir=self.extension_dir if self.summary.captcha == True else None
        )
```
Logic:
```
target = "https://netguard.io/sduyafgewsdfn.php" # Website with cf captcha
self.session = self.create()
self.session.uc_open(target)
self.session.reconnect(2.55 if not self.summary.emulation_force else 6.0)

# In here getting Cloudflare captcha loop
try:
    self.session.switch_to_frame("iframe")
    self.session.uc_click("span")
    self.session.switch_to.default_content()
    self.session.sleep(3.5)
except Exception: pass
```

Worth to add I have tested on my local IP address, tested on proxyscrape.com dedicated proxies and rotating ones and also other provider with IPv6 proxies. On all proxy versions same issue.

**Comment by JimKarvo** [comment]
I have this code (tryied also with incognito):

```
from seleniumbase import SB
import time 

with SB(uc=True, test=True) as sb:
    url = "https://visa.vfsglobal.com/fra/en/hrv/login"
    sb.driver.uc_open_with_reconnect(url, 6)
    sb.switch_to_frame("iframe")
    sb.driver.uc_click("span")
    time.sleep(3)
    sb.save_screenshot("bypass.png")
```

at windows, I get the CF passed. 
at Linux, i get the CF not clicked

windows 11:
![bypass](https://github.com/seleniumbase/SeleniumBase/assets/84914040/3fdbbce9-237a-45c3-bf2d-ea3fbac86d13)

linux - ubuntu server 20.04:
![bypass](https://github.com/seleniumbase/SeleniumBase/assets/84914040/d1bbce97-bd56-4475-933e-987b3865c0ae)

**Comment by mdmintz** [comment]
@JimKarvo Thank you... That is helpful. I see the same thing: Working on both macOS and Windows, but not for Linux (Ubuntu server 20.04). I will look into improvements specifically on the Ubuntu side (since things appear to be working on macOS and Windows, at least with `incognito=True`). Possibly Cloudflare found a way to see if automation is running on Ubuntu.

I'll be working on improvements to SeleniumBase Ubuntu configuration. In the meantime, people can keep passing on any information that I might find useful. (If anyone is still having macOS or Windows issues, I'll need an example that reproduces your issue, because so far things appear to be normal on the local desktop front, at least with `incognito=True`.)

**Comment by JimKarvo** [comment]
I don't know, but changine any user agent, maybe will help the situation?

If I can help with access to any of my VMs (ubuntu server), I can send ssh details

**Comment by mdmintz** [comment]
@JimKarvo Can you tell me the user-agent that appears when you ran on Ubuntu? And the agent you saw when running locally? Maybe there's a clue there.

**Comment by JimKarvo** [comment]
@mdmintz 

From Linux I get:

```
GET / HTTP/1.1
Host: test.requestcatcher.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Sec-Ch-Ua: "Chromium";v="125", "Not.A/Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Linux"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.141 Safari/537.36
```

from Windows I get:

```
GET /test HTTP/1.1
Host: test.requestcatcher.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: el-GR,el;q=0.9
Connection: keep-alive
Sec-Ch-Ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
```

**Comment by mdmintz** [comment]
If there's a human-controlled web browser with that same user-agent on that system (`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.141 Safari/537.36`) I'm wondering if they would experience the same issue. Anyone having any issues if they use a Linux computer with a GUI and a regular web browser? (Possibly Cloudflare is only blocking based on that agent - not because they detected Selenium.)

**Comment by OpsecGuy** [comment]
> @JimKarvo Thank you... That is helpful. I see the same thing: Working on both macOS and Windows, but not for Linux (Ubuntu server 20.04). I will look into improvements specifically on the Ubuntu side (since things appear to be working on macOS and Windows, at least with `incognito=True`). Possibly Cloudflare found a way to see if automation is running on Ubuntu.
> 
> I'll be working on improvements to SeleniumBase Ubuntu configuration. In the meantime, people can keep passing on any information that I might find useful. (If anyone is still having macOS or Windows issues, I'll need an example that reproduces your issue, because so far things appear to be normal on the local desktop front, at least with `incognito=True`.)

Not really. As mentioned by me above. I still struggle with bypassing on Windows. I don't know if there is anything else I could add to it. If you need more info tell me exactly what should I be looking for.

**Comment by mdmintz** [comment]
@OpsecGuy You seem to be the only one having Windows issues at this time. You also introduced a lot of variables into the equation in your example. Eg. 1. using `Driver()` instead of `SB()`. 2. Using Dark Mode. 3. Using any headless mode. 4. Changing proxy settings. 5. Adding an extension. You should stick with the specific examples I tried in this thread (or another UC Mode example from the `SeleniumBase/examples` folder) for debugging purposes.

**Comment by Jobine23** [comment]
I am using a VPS using Windows server 2022, without GPU. incognito=True does not appear to help

Incognito:

```
with SB(uc=True, test=True, incognito=True) as sb:
    url = "https://visa.vfsglobal.com/fra/en/hrv/login"
    sb.driver.uc_open_with_reconnect(url, 8)
    sb.switch_to_frame("iframe")
    sb.driver.uc_click("span")
    breakpoint()
```
![sb_fail_incognito](https://github.com/seleniumbase/SeleniumBase/assets/30392487/4a9acd6c-c8a3-45df-86c7-eb91e73d19f8)


```
with SB(uc=True, test=True) as sb:
    url = "https://visa.vfsglobal.com/fra/en/hrv/login"
    sb.driver.uc_open_with_reconnect(url, 8)
    sb.switch_to_frame("iframe")
    sb.driver.uc_click("span")
    breakpoint()
```

![sb_fail](https://github.com/seleniumbase/SeleniumBase/assets/30392487/f7c1fa7b-9df6-4f05-8662-7ac326c90d86)


It is not related to any ratelimiting because I am able to click complete Turnstile captcha inside the same environment/computer, but in a real chrome ( latest 125.0.6422.142 ) instance:

![real_chrome](https://github.com/seleniumbase/SeleniumBase/assets/30392487/9dd81839-3e9b-4ef5-b80d-8b656d677aeb)


I found something rather interesting comparing both browser info from https://bot.incolumitas.com/ ( both tests executed on the same machine ).

Regular chrome:
https://pastebin.com/raw/fj3uaNBM

SB with UC=True:
https://pastebin.com/raw/AiV3y58D

SeleniumBase appears to be missing some navigatorProperties/navigatorPrototype. I have no idea if it could impact but I guess it should be as similar as possible to a fresh chrome instance.

**Comment by EnmeiRyuuDev** [comment]
I think the focus should be on the **switch_to_frame**/ **uc_click** action.
Because with manual click (after **uc_open_with_reconnect**) it works smoothly (whether we're under Linux or Windows, Desktop or Server).
Still puzzling why **uc_click** still work in a Desktop environment.

**Comment by Jobine23** [comment]
Yes, `sb.driver.uc_open_with_reconnect(url, 99999)` and clicking manually appears to work for me so I guess it's not related to what I sent previously.

**Comment by mdmintz** [comment]
OK, I'm trying to figure out why `uc_click(selector)` behaves differently in different environments (Linux vs macOS/Windows). I'll hopefully have an update ready soon / early this week.

If anyone figures out the reason for the `uc_click(selector)` differences before I do, let me know. The good news is that `sb.driver.uc_open_with_reconnect(url, reconnect_time)` is working correctly, and that's the main component of UC Mode.

Hopefully there's a `pyautogui` alternative to clicking in a stealthy way. Currently, that is an option. Eg. If you use `driver.uc_open_with_disconnect(url)`, then you can use `pyautogui` to click in a stealthy way, followed by `driver.connect()` so that you can perform more Selenium actions after that.

**Comment by JimKarvo** [comment]
Tried to implent pyautogui, with no luck, so in case that anybody have working example gor headless systems, that pyautogui working, please write below!

Thank you!

**Comment by mdmintz** [comment]
@JimKarvo `pyautogui` won't work for headless browsers, or multithreaded, but if you wanted to see an example script that uses `pyautogui`, here's one:

```python
import pyautogui
from seleniumbase import SB

with SB(uc=True, test=True, incognito=True) as sb:
    sb.driver.uc_open_with_reconnect("https://seleniumbase.io/apps/turnstile")
    sb.send_keys("html", "\t")
    sb.driver.disconnect()
    pyautogui.press(" ")
    sb.sleep(1)
    sb.driver.connect()
    sb.assert_element("img#captcha-success", timeout=3)
    sb.set_messenger_theme(location="top_left")
    sb.post_message("SeleniumBase wasn't detected", duration=3)
```

Obviously, due to those `pyautogui` limitations, I want a better workaround for Ubuntu Servers.
At least macOS and Windows are still good for now. (And yes, I'm working on Ubuntu solutions.)

**Comment by JimKarvo** [comment]
Guys, I found that changing the user agent, to a valid one, bypasses the CF.
EG: I tryied this:

```
ua = "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.2 (KHTML, like Gecko) Chrome/94.0.4096.99 Safari/534.2 EdgA/94.01135.87"


with SB(uc=True, test=True, agent=ua) as sb:
```

@mdmintz are there any changes that we can modify the `Sec-Ch-Ua-Platform: "Linux"` in order to tell the CF that we are using windows (for future blocks?)

**Comment by vmolostvov** [comment]
> Guys, I found that changing the user agent, to a valid one, bypasses the CF. EG: I tryied this:
> 
> ```
> ua = "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.2 (KHTML, like Gecko) Chrome/94.0.4096.99 Safari/534.2 EdgA/94.01135.87"
> 
> 
> with SB(uc=True, test=True, agent=ua) as sb:
> ```
> 
> @mdmintz are there any changes that we can modify the `Sec-Ch-Ua-Platform: "Linux"` in order to tell the CF that we are using windows (for future blocks?)

Changing the UA did not yield any results on ubuntu vds. Tried more than 5 different values. Are you using Linux with GUI ?

**Comment by JimKarvo** [comment]
You are right, after a lot of tests I found that passing a valid user agent just triggers the anti-bot system of cloudflare less than before. 

Also I noticed that the checkbox is clicked and trying to resolve the I am human with no luck. 

@mdmintz sounds like the main problem is not just the click of span element

**Comment by mdmintz** [comment]
I don't think it's the UA. People said that using `sb.driver.uc_open_with_reconnect(url, reconnect_time)` followed by a manual click works on Ubuntu (with a GUI). That means it's a problem with `uc_click(selector)` somehow.

Or maybe people should recheck that... if anyone uses `sb.driver.uc_open_with_reconnect(url, reconnect_time)` on Ubuntu and manually clicks before the `reconnect_time` expires, does it work consistently?

**Comment by mdmintz** [comment]
I found something interesting. If I do the following **on a Mac** (with a **Linux UA**), and click manually before the `reconnect_time` expires, then the CAPTCHA is bypassed successfully. But if I wait for the `uc_click(selector)` to happen, then it fails:

```python
from seleniumbase import SB

agent=("Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.2 (KHTML, like Gecko) Chrome/94.0.4096.99 Safari/534.2 EdgA/94.01135.87")

with SB(uc=True, test=True, agent=agent) as sb:
    url = "https://visa.vfsglobal.com/fra/en/hrv/login"
    sb.driver.uc_open_with_reconnect(url, 15)
    sb.switch_to_frame("iframe")
    sb.driver.uc_click("span")
    breakpoint()
```

So as long as Selenium is not detected during the `uc_click(selector)` part, it doesn't seem like they cared that there was a Linux UA for a macOS system.

**Comment by mdmintz** [comment]
OK, here's the full scope:

UC Mode:
--> macOS: ✅ (All good)
--> Windows: ✅ (All good)
--> Linux (Ubuntu / server): ⁉️ (conditional)
------> `uc_open_with_reconnect()`: ✅
----------> Manual actions (while disconnected): ✅
----------> `pyautogui` actions (while disconnected): ✅
----------> `uc_click(selector)`: ❌

I'll be working on either fixing `uc_click(selector)` on Linux, or an alternative way to successfully clicking a CAPTCHA checkbox on Linux.

**Comment by poplu2525** [comment]
I am using inside the docker file(ubuntu), if i click manually as soon as captcha pops up, it gets resolve, otherwise its not.
i used PyautoGui also , Not working

**Comment by poplu2525** [comment]
got it working guys, implemented the crazy solution, Launched 2 threads, 1 thread will handle seleniumbase and another will handle pyautogui and we are good to go

**Comment by JimKarvo** [comment]
> got it working guys, implemented the crazy solution, Launched 2 threads, 1 thread will handle seleniumbase and another will handle pyautogui and we are good to go

This will not work at headless systems although

**Comment by mdmintz** [comment]
So for macOS and Windows, the User Agent is automatically set to a "good" one, and the CAPTCHA gets bypassed successfully, automatically:

```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://visa.vfsglobal.com/fra/en/hrv/login"
    sb.driver.uc_open_with_reconnect(url, 12)
```

If you use Linux or set your User Agent to a "not that good" one, then you will be forced to click on the CAPTCHA to bypass it (and due to Cloudflare's recent updates, you'll need to use `pyautogui` to make it work):

```python
import pyautogui
from seleniumbase import SB

agent=("Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.2 (KHTML, like Gecko) Chrome/94.0.4096.99 Safari/534.2 EdgA/94.01135.87")

with SB(uc=True, test=True, agent=agent) as sb:
    url = "https://visa.vfsglobal.com/fra/en/hrv/login"
    sb.driver.uc_open_with_reconnect(url, 12)
    sb.switch_to_frame("iframe")
    sb.execute_script('document.querySelector("input").focus()')
    sb.disconnect()
    pyautogui.press(" ")
    sb.driver.reconnect(4)
```

Rumor has it that if you set the correct User Agent on Linux, then the CAPTCHA gets bypassed automatically, like in the current macOS and Windows versions.

I can simplify the `pyautogui` stuff to a single line in a near future version of `seleniumbase`. Hopefully, there's a way to avoid `pyautogui` entirely when needing to click the CAPTCHA checkbox.

Here's how you can help:
* If you can figure out the "magic" User Agent to use on Linux, let me know.
* If you can figure out a way to successfully click the CAPTCHA without `pyautogui` now, let me know.

**Comment by JimKarvo** [comment]
@mdmintz I don't think that changing only the useragent will solve the problem.

At request we can see that the user agent is a good on (Windows etc) but the chrome is running under linux
`Sec-Ch-Ua-Platform: "Linux"`
is it possible to change parameters like that?



> @mdmintz
> 
> From Linux I get:
> 
> ```
> GET / HTTP/1.1
> Host: test.requestcatcher.com
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
> Accept-Encoding: gzip, deflate, br, zstd
> Accept-Language: en-US,en;q=0.9
> Connection: keep-alive
> Sec-Ch-Ua: "Chromium";v="125", "Not.A/Brand";v="24"
> Sec-Ch-Ua-Mobile: ?0
> Sec-Ch-Ua-Platform: "Linux"
> Sec-Fetch-Dest: document
> Sec-Fetch-Mode: navigate
> Sec-Fetch-Site: cross-site
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.141 Safari/537.36
> ```
> 
> from Windows I get:
> 
> ```
> GET /test HTTP/1.1
> Host: test.requestcatcher.com
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
> Accept-Encoding: gzip, deflate, br, zstd
> Accept-Language: el-GR,el;q=0.9
> Connection: keep-alive
> Sec-Ch-Ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
> Sec-Ch-Ua-Mobile: ?0
> Sec-Ch-Ua-Platform: "Windows"
> Sec-Fetch-Dest: document
> Sec-Fetch-Mode: navigate
> Sec-Fetch-Site: cross-site
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
> ```

**Comment by mdmintz** [comment]
@JimKarvo Try this on Linux:

```python
from seleniumbase import SB

with SB(uc=True, test=True, disable_features="UserAgentClientHint") as sb:
    url = "https://visa.vfsglobal.com/fra/en/hrv/login"
    sb.driver.uc_open_with_reconnect(url, 15)
    breakpoint()
```

The `"UserAgentClientHint"` should remove the `Sec-Ch-Ua-Platform`.
If that works, I'll make it permanent for UC Mode on Linux. Let me know!

**Comment by sakarimov** [comment]
> @JimKarvo Try this on Linux:
> 
> ```python
> from seleniumbase import SB
> 
> with SB(uc=True, test=True, disable_features="UserAgentClientHint") as sb:
>     url = "https://visa.vfsglobal.com/fra/en/hrv/login"
>     sb.driver.uc_open_with_reconnect(url, 15)
>     breakpoint()
> ```
> 
> The `"UserAgentClientHint"` should remove the `Sec-Ch-Ua-Platform`. If that works, I'll make it permanent for UC Mode on Linux. Let me know!

tried this, and still get the error


https://github.com/seleniumbase/SeleniumBase/assets/5676876/eb208958-90ad-46c0-abfd-3a0f6089b322

**Comment by mdmintz** [comment]
@sakarimov You may also need to change your User `agent` to one that doesn't have `Linux` in it.
If you change that too, is there any difference?

**Comment by jens4626** [comment]
@Jobine23 did you get it working on VPS running Windows Server 2022? @mdmintz  I ran this as you have suggest on Windows in incognito, but it gets detected and doesn't get through the verification. 

with SB(uc=True, test=True, incognito=True) as sb:

    url = "https://www.virtualmanager.com/da/login?ref_url="
    sb.driver.uc_open_with_reconnect(url, 20)
    sb.switch_to_frame("iframe")
    sb.driver.uc_click("span")

https://github.com/seleniumbase/SeleniumBase/assets/45258332/908d7013-fa8a-4670-9986-83cef1b6374c

**Comment by mdmintz** [comment]
@jens4626 What's the default User Agent that appears when running on your Windows Server?
You can use `print(sb.get_user_agent())` to get the string.

**Comment by sakarimov** [comment]
> @sakarimov You may also need to change your User `agent` to one that doesn't have `Linux` in it. If you change that too, is there any difference?

it works for me


https://github.com/seleniumbase/SeleniumBase/assets/5676876/c4bd1b29-0101-4a66-ba8d-40a1b9d0f8f9

**Comment by JimKarvo** [comment]
@mdmintz I tryied this one, after failing to resolve the captcha

look like the `disable_features="UserAgentClientHint"` not working at all

```
from seleniumbase import SB

ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
with SB(uc=True, test=True, disable_features="UserAgentClientHint", agent=ua) as sb:
    print("getting req catcher") 
    url = "https://jimkarvo.requestcatcher.com/test"
    sb.driver.uc_open_with_reconnect(url, 1)
    breakpoint()
```

the data i received:

```
GET /test HTTP/1.1
Host: jimkarvo.requestcatcher.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Sec-Ch-Ua: "Chromium";v="125", "Not.A/Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
**Sec-Ch-Ua-Platform: "Linux"**
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
**User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0** Safari/537.36
```

**Comment by sakarimov** [comment]
> ```
> from seleniumbase import SB
> 
> ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
> with SB(uc=True, test=True, disable_features="UserAgentClientHint", agent=ua) as sb:
>     print("getting req catcher") 
>     url = "https://jimkarvo.requestcatcher.com/test"
>     sb.driver.uc_open_with_reconnect(url, 1)
>     breakpoint()
> ```

@JimKarvo your reconnect duration seems too small, make it bigger like 7 / 8, in my case  i use 20 and it works just fine

**Comment by JimKarvo** [comment]
> > ```python
> > from seleniumbase import SB
> > 
> > ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
> > with SB(uc=True, test=True, disable_features="UserAgentClientHint", agent=ua) as sb:
> >     print("getting req catcher") 
> >     url = "https://jimkarvo.requestcatcher.com/test"
> >     sb.driver.uc_open_with_reconnect(url, 1)
> >     breakpoint()
> > ```
> 
> @JimKarvo your reconnect duration seems too small, make it bigger like 7 / 8, in my case i use 20 and it works just fine

the above code, it's just for getting the user-agent and all data that browser sends to a server while request a page.

**Comment by mdmintz** [comment]
@JimKarvo  This site is a good one for seeing all the headers: https://browserleaks.com/client-hints
@jens4626 My Windows machine had the same UA, and bypassed without issue.
@sakarimov Seeing similar. Changing the User Agent makes a difference.

So what have we learned? Cloudflare made changes. Previously, they only blocked you if they detected Selenium, but now they are blocking you for other things, such as User Agent.

Three types of User Agents now (in combination with UC Mode):
* **Good**: Bypass CAPTCHA immediately.
* **Not that good**: You have to click the CAPTCHA in a stealthy way to bypass it.
* **Really bad**: Blocked immediately. (Eg. You have `HeadlessChrome` in your User Agent.)

You may have to change your User Agent on Linux to be "Good".

For the "Not that good", you'll need to use `pyautogui` to click. (They are currently detecting any type of JS used to click Turnstile checkboxes, even with `uc_click`.)

This should work every time as long as the machine has a GUI:

```python
from seleniumbase import SB

ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"

with SB(uc=True, test=True, agent=ua, disable_features="UserAgentClientHint", incognito=True) as sb:
    url = "https://www.virtualmanager.com/da/login"
    sb.driver.uc_open_with_reconnect(url, 8)
    if sb.is_element_visible("iframe"):
        sb.switch_to_frame("iframe")
        sb.execute_script('document.querySelector("input").focus()')
        sb.disconnect()
        pyautogui.press(" ")
        sb.driver.reconnect(4)
    breakpoint()
```

**Comment by jens4626** [comment]
Thanks @mdmintz!
Workaround using pyautogui does indeed work - I do hope to see a fix using uc_click fix soon!

**Comment by jens4626** [comment]
Sadly the pyautogui does not always seems to bypass.
Hope you're working on a uc_click fix :)

**Comment by mdmintz** [comment]
@jens4626 Make sure all your `pyautogui` actions happen after the `sb.disconnect()`. Then when done, call `sb.connect()` / `sb.reconnect()` to use Selenium actions again.

**Comment by jens4626** [comment]
@mdmintz It does work - but its only 50% chance that it works.

I currently have 3 situations: 

1. The space bar presses doesn't get recognized so it won't bypass - I tried adding a few more hoping it would solve it, but negative.
2. It does recognize space bar pressing as click but Cloudflare detects it, so it will loop through again.
3. It sends the space bar and it bypasses Cloudflare.

I did use that code you provided and it works - but just not always.

So not sure what to do tbh.

`            sb.switch_to_frame("iframe")
            print("Switched to iframe")
            
            # Waiting to ensure the iframe is loaded
            time.sleep(2)
            
            # Focus on the input element
            sb.execute_script('document.querySelector("input").focus()')
            time.sleep(2)
            
            # Disconnecting the SeleniumBase driver
            print("Disconnecting SB")
            sb.disconnect()
            time.sleep(2)
            
            # Press the space bar with a short delay in between
            pyautogui.press(" ")
            time.sleep(1)
            pyautogui.press(" ")
            time.sleep(1)
            pyautogui.press(" ")
            time.sleep(1)
            pyautogui.press(" ")
            print("Pressed space four times")
            
            # Waiting for the actions to complete
            time.sleep(2)
            
            # Reconnecting the SeleniumBase driver
            print("Reconnecting SB")
            sb.driver.reconnect(4)
            
`

**Comment by mdmintz** [comment]
@jens4626 The spacebar from `pyautogui` might not get recognized if your Selenium window is not the active window on top. Try that (making sure the window is on top and active) while I'm still working on improvements...

**Comment by ismayilibrahimov** [comment]
This was also not working for me when disconnecting from remote windows 10 (azure vm). So as @mdmintz mentioned, we have to keep chrome window active. 

Updated code:
```
from seleniumbase import SB

ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"

with SB(uc=True, test=True, agent=ua, disable_features="UserAgentClientHint", incognito=True) as sb:
    url = "https://www.virtualmanager.com/da/login"
    sb.driver.uc_open_with_reconnect(url, 8)
    if sb.is_element_visible("iframe"):
        sb.switch_to_frame("iframe")
        sb.execute_script('document.querySelector("input").focus()')
        sb.driver.maximize_window()
        sb.disconnect()
        pyautogui.press(" ")
        sb.driver.reconnect(4)
    breakpoint()
```

As a note, when I disconnect from remote desktop, windows gui is disabled. So, in order to keep your current session active, you can use this [instruction](https://stackoverflow.com/questions/15887729/can-the-gui-of-an-rdp-session-remain-active-after-disconnect).

**Comment by SaberTawfiq** [comment]
I test https://github.com/sarperavci/CloudflareBypassForScraping the script uses the DrissionPage
When you open the browser normally, it automatically succeeds without clicking to confirm that you are a human. 
When verify you are human appears, he clicks on the box and success is given. Can you merge or modify uc_click to work on the same principle on the Seleniumbase

**Comment by EnmeiRyuuDev** [comment]
> I test https://github.com/sarperavci/CloudflareBypassForScraping the script uses the DrissionPage When you open the browser normally, it automatically succeeds without clicking to confirm that you are a human. When verify you are human appears, he clicks on the box and success is given. Can you merge or modify uc_click to work on the same principle on the Seleniumbase

I confirm, the DrissionPage solution bypasses the cloudflare click under Linux.

**Comment by EnmeiRyuuDev** [comment]
The **pyautogui.press(" ")** solution works consistently as well under Linux.
You can make it work in headless mode, and in a multi-process environment, by attaching it to a virtual monitor.
This code worked for me under Ubuntu/ Debian (note that **Headed=True**; but Selenium will run anyway headless)..

```
from seleniumbase import SB
import pyautogui
from pyvirtualdisplay.display import Display
disp = Display(visible=True, size=(1366, 768), backend="xvfb", use_xauth=True)
disp.start()

import Xlib.display
pyautogui._pyautogui_x11._display = Xlib.display.Display(os.environ['DISPLAY'])

with SB(uc=True, headed=True) as sb:
     ...
```

**Comment by mdmintz** [comment]
@EnmeiRyuuDev SeleniumBase uses the built-in `sbvirtualdisplay` like this:

```python
self._xvfb_display = Display(visible=0, size=(width, height))
self._xvfb_display.start()
```

Will that work with the code you added?

```python
import Xlib.display
pyautogui._pyautogui_x11._display = Xlib.display.Display(os.environ['DISPLAY'])
```

I assume you installed this: `python-xlib`?
Does `pyautogui` need that to succeed on Linux?

**Comment by EnmeiRyuuDev** [comment]
@mdmintz in my tests, this piece of code was required:
```
from pyvirtualdisplay.display import Display
disp = Display(visible=True, size=(1366, 768), backend="xvfb", use_xauth=True)
disp.start()
```
Otherwise, Selenium will not run headless.

Also, `headed=True` was required but still SB runs headless which is perfect, otherwise `pyautogui` will not work.
Also, the code will not work under Windows, only valid under Linux. I remember I only had to install the `pyvirtualdisplay`.
Also in the Linux environment, some packages are necessary:
`sudo apt-get install python3.10-tk python3-dev tk-dev`
And rebuilding the Python afterwards:
```
sudo ./configure --enable-optimizations
sudo make -j 2
sudo make altinstall
```

This my complete test code:

```
import os
from seleniumbase import SB
import time
import sys
import random
import math
import pyautogui

from pyvirtualdisplay.display import Display
disp = Display(visible=True, size=(1366, 768), backend="xvfb", use_xauth=True)
disp.start()

import Xlib.display
pyautogui._pyautogui_x11._display = Xlib.display.Display(os.environ['DISPLAY'])


with SB(uc=True, headed=True, proxy=None) as sb:
    print('Started..')
    url = "https://gitlab.com/users/sign_in"
    sb.driver.uc_open_with_reconnect(url, 10)
    if sb.is_element_visible("iframe"):
        sb.switch_to_frame("iframe")
        sb.execute_script('document.querySelector("input").focus()')
        sb.disconnect()
        print('Click..')
        pyautogui.press(" ")
        sb.driver.reconnect(10)
    random_number = random.randint(1000, 9999)
    filename = f"screenshot_{random_number}.png"
    sb.save_screenshot(filename)
    print('End.')
```

What was interesting, is that when running multiple headless instances (+20 chrome driver instances), they all click independently without that window overlapping issue.

**Comment by jens4626** [comment]
Thanks for the input @mdmintz  and @ismayilibrahimov.

I think the issue with not clicking was due to me.
But I still face issues with it not being able to bypass as you can see:
https://github.com/seleniumbase/SeleniumBase/assets/45258332/ee31069b-8d09-4210-9d70-cac90e5a4b18

It might be caused by bad IP score and now using pyautogui - it was never an issue with uc.click. 

I was already using what you mentioned @ismayilibrahimov so thats not the problem either.

**Comment by DiegoDA04** [comment]
Please, resolve this issue, because my partner dosn't cant scrape her BL novels. I mean not funca (she works in google colab) xd

**Comment by mdmintz** [comment]
More details:

Now, if your User-Agent looks untrustworthy, CloudFlare makes you click the CAPTCHA (which has been improved). If they detect **either** Selenium in the browser **or** JavaScript involvement in clicking the CAPTCHA, they don't let the click through. That's why `pyautogui` is now required for clicking the CAPTCHA **if** the User-Agent isn't trustworthy enough. The default user-agent set on macOS and Windows by SeleniumBase **is** *generally* good enough. On Linux, the default User-Agent might not be good enough: You may need to specify a better one to avoid needing to click the CAPTCHA in that scenario. (Or just use the `pyautogui` workaround for clicking it... Scroll up to see some examples that use it.)

I'm working on an update that can optionally utilize the `pyautogui` workaround if needed. That will likely need an update to examples because the existing `uc_click` might not be good enough *if* the User-Agent isn't trustworthy enough.

This probably means a new UC Mode Video Tutorial (Part 3) is likely to happen soon to explain the changes.

**Comment by ismayilibrahimov** [comment]
I am using windows 10 (without headless mode) at azure, and CloudFlare requires to click. I think user-agent is not the only issue

> More details:
> 
> Now, if your User-Agent looks untrustworthy, CloudFlare makes you click the CAPTCHA (which has been improved). If they detect **either** Selenium in the browser **or** JavaScript involvement in clicking the CAPTCHA, they don't let the click through. That's why `pyautogui` is now required for clicking the CAPTCHA **if** the User-Agent isn't trustworthy enough. The default user-agent set on macOS and Windows by SeleniumBase **is** _generally_ good enough. On Linux, the default User-Agent might not be good enough: You may need to specify a better one to avoid needing to click the CAPTCHA in that scenario. (Or just use the `pyautogui` workaround for clicking it... Scroll up to see some examples that use it.)
> 
> I'm working on an update that can optionally utilize the `pyautogui` workaround if needed. That will likely need an update to examples because the existing `uc_click` might not be good enough _if_ the User-Agent isn't trustworthy enough.
> 
> This probably means a new UC Mode Video Tutorial (Part 3) is likely to happen soon to explain the changes.

**Comment by mdmintz** [comment]
@ismayilibrahimov Azure has a known IP-range (just like AWS or GCP). That's why residential proxies have become so popular lately for web-scraping.

**Comment by enricodvn** [comment]
Were you guys able to use this alternative with proxy?

So, for me CF started showing the challenge the same time around, and it only happens when I am using proxy (on servers).

Local without proxy it works fine. But when I use proxy, even on local env, bam there is the captcha. They somehow are detecting the proxy.

If I try to use the alternative with pyautogui, it works without proxy, but if I use proxy this is what happens:

![asd1](https://github.com/seleniumbase/SeleniumBase/assets/19861996/67599565-e6fb-4a48-b3d0-388b01f2f5f8)

**Comment by mdmintz** [comment]
@enricodvn Which alternative are you using? The one with `Xlib.display`? As for proxies, I haven't seen any local issues with using them, although maybe it works better when the time zone of the proxy is in the same time zone as your browser.

**Comment by enricodvn** [comment]
Yes, the last one from https://github.com/seleniumbase/SeleniumBase/issues/2842#issuecomment-2168829685.

Hmm, this time zone setting is interesting, anyway I can set it through driver?

I will try to tweak with it.

**Comment by mdmintz** [comment]
@enricodvn The time zone can be set via `execute_cdp_cmd`, but CDP changes go away when the driver is disconnected. Would need a way to configure it before the browser is launched. (Also possible that it's unrelated to the time zone difference.)

**Comment by ankushkumarpatiyal** [comment]
def open_the_turnstile_page(sb,url):
        url = url
        sb.driver.uc_open_with_reconnect(url, 15)
        print('getting websie')
        screen = 'new.jpg'
        sb.save_screenshot(os.path.join(settings.MEDIA_ROOT,screen))
        if sb.is_element_visible("iframe"):
            print('inside if')
            sb.switch_to_frame("iframe")
            sleep(1)
            print('iframe found')
            sb.execute_script('document.querySelector("input").focus()')
            sb.disconnect()
            pyautogui.press(" ")
            print('pressed')
            file='new_screenshot.png'
            print('file saved')
            sb.driver.reconnect(3)
            sb.save_screenshot(os.path.join(settings.MEDIA_ROOT,file))
        random_number = random.randint(1000, 9999)
        filename = f"screenshot_{random_number}.png"
        sb.save_screenshot(os.path.join(settings.MEDIA_ROOT,filename))
        print('saved screenshot')
        page_source = sb.get_page_source()
        print(page_source)
        
        
        most of the time after pyautogui presses and i get print statement in my console('pressed') my code stops there like it doesnt fail but still it gets stuck, why? can anyone help me out here and i am on ubuntu server and on local machine everything works just fine

**Comment by mdmintz** [comment]
This was resolved in `4.28.0` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.28.0

Read https://github.com/seleniumbase/SeleniumBase/issues/2865 for all the details. You may need to use the new UC Mode methods in `4.28.0`, such as `driver.uc_gui_handle_cf()`, in order to successfully click through CF CAPTCHA checkboxes on Linux.

**Comment by wnx3** [comment]
Using `sb.uc_gui_handle_cf()`, if I don't touch the computer while the script is running, I can pass the cloudflare captcha normally, now if I need to touch the computer, it doesn't solve the captcha.
I'm running on Windows, and I'm also having problems with cloudflare captcha.

**Comment by enricodvn** [comment]
It is working for ubuntu (locally). But on remote servers, with residential proxies, I could not make it work.

In the end I just switched to remote mac machines... Somehow CF just trust you if you are an apple user.

**Comment by TyronMYoung11** [comment]
@mdmintz No man, it's not IP-Block! Because of 2 reasons:
1- My Ubuntu Server VM is on my network and Windows and Ubuntu Server both has same IP
2- When i save screenshot, i see the captcha is in idle state! mean, the sb never clicks the square button and never triggered it!
Note the Captcha is not hard, mean it's not even need to solve any puzzle, just need to click the checkbox and it passes
