### ISSUE TITLE
Disable "passkey" pop-ups

### ISSUE THREAD

**Issue by mdmintz** [seleniumbase/SeleniumBase#4141]
## Disable "passkey" pop-ups

Someone from the SeleniumBase Discord Server (https://discord.gg/EdhQTn3EyE) reported that there was a new "passkey" pop-up appearing for some sites. This pop-up should be prevented. (It's caused by Google Password Manager settings on Chrome.)

<img width="500" height="356" alt="Image" src="https://github.com/user-attachments/assets/18e01948-2b23-4125-a0ef-b0d6d28c23c3" />

**Comment by mdmintz** [comment]
This was resolved in `4.44.20` - https://github.com/seleniumbase/SeleniumBase/releases/tag/v4.44.20

**Comment by Muhammad-Soban** [comment]
@mdmintz 
I’m still facing the passkey dialog issue on Amazon.com sign-in

**Environment:**
- selenium==4.39.0
- seleniumbase==4.45.1
- Chrome Version: 143.0.7499.110
- Python: 3.12.6
- macOS: 26.1

**Issue:**
Chrome continues to show the Passkey / WebAuthn prompt during Amazon login, which interrupts automation. I would like to know if there is any way to disable or automatically close this dialog using SeleniumBase.

<img width="932" height="524" alt="Image" src="https://github.com/user-attachments/assets/15f3abe8-0683-4bb0-af7e-2fa72a643371" />

**Comment by mdmintz** [comment]
Have you tried `guest=True` or `incognito=True`?

**Comment by Muhammad-Soban** [comment]
I also tried using incognito=True, but the Passkey dialog still appeared.
Next, I tried guest=True, but instead Chrome showed this error instead:

Chrome needs permission to use Bluetooth to connect to your device

<img width="987" height="617" alt="Image" src="https://github.com/user-attachments/assets/b971cf44-d20e-4058-a884-03eea1b889a0" />

**Comment by mdmintz** [comment]
Try with `chromium_arg="--disable-bluetooth,--disable-bluetooth-low-energy,--disable-bluetooth-discovery,--disable-web-bluetooth"` to prevent that pop-up.

**Comment by Muhammad-Soban** [comment]
I tried it, but it's still not working.
Here is my code:
```
from seleniumbase import SB

with SB(
    uc=True,
    guest=True,
    chromium_arg="--disable-bluetooth,--disable-bluetooth-low-energy,--disable-bluetooth-discovery,--disable-web-bluetooth"
) as sb:
    ...
```

**Comment by mdmintz** [comment]
Can you send a full script that reproduces the issue without logging in?

**Comment by Muhammad-Soban** [comment]
Here is full script

```
from celery import shared_task
from seleniumbase import SB


def get_headless_options():
    return {"headless1": True, "headless2": True, "headless": True}


def wait_for_element_clickable_and_type(selenium_base_context, element_xpath, value, timeout=30):
    selenium_base_context.wait_for_element_clickable(element_xpath, timeout=timeout)
    selenium_base_context.type(element_xpath, value)


def wait_for_element_clickable_and_click(selenium_base_context, element_xpath, timeout=30):
    selenium_base_context.wait_for_element_visible(element_xpath, timeout=timeout)
    selenium_base_context.wait_for_element_clickable(element_xpath, timeout=timeout)
    selenium_base_context.click(element_xpath)


@shared_task
def download_report():
    with SB(
            **get_headless_options(), uc=True, guest=True,
            chromium_arg="--disable-bluetooth,--disable-bluetooth-low-energy,--disable-bluetooth-discovery,--disable-web-bluetooth"
    ) as sb:
        sb.open('https://kdpreports.amazon.com/dashboard')
        sb.sleep(5)

        email_login_xpath = '//*[@id="ap_email"]'
        continue_button_xpath = '//*[@id="continue"]'
        password_login_xpath = '//*[@id="ap_password"]'
        sign_in_submit_button_xpath = '//*[@id="signInSubmit"]'

        sb.sleep(5)

        if 'signin' in sb.get_current_url().lower():
            # signin url https://www.amazon.com/ap/signin
            wait_for_element_clickable_and_type(sb, email_login_xpath, 'your_email')
            wait_for_element_clickable_and_click(sb, continue_button_xpath)
            sb.sleep(5)
            wait_for_element_clickable_and_type(sb, password_login_xpath, 'your_password')
            wait_for_element_clickable_and_click(sb, sign_in_submit_button_xpath)
            sb.sleep(5)
```

**Comment by mdmintz** [comment]
This gets you to that page, without the pop-up.
```python
from seleniumbase import SB

with SB(uc=True, test=True) as sb:
    url = "https://kdpreports.amazon.com/dashboard"
    sb.activate_cdp_mode(url)

    breakpoint()
```
Since the rest requires a log-in, I can't really help from there.

**Comment by Muhammad-Soban** [comment]
I can’t use guest=True because I need to download the report, and in guest mode the browser shows a file-save dialog that I’m unable to interact with. Is there any other way to disable the passkey prompt?

Here is my updated script:
```
from celery import shared_task
from seleniumbase import SB


def get_headless_options():
    return {"headless1": True, "headless2": True, "headless": True}


def wait_for_element_clickable_and_type(selenium_base_context, element_xpath, value, timeout=30):
    selenium_base_context.wait_for_element_clickable(element_xpath, timeout=timeout)
    selenium_base_context.type(element_xpath, value)


def wait_for_element_clickable_and_click(selenium_base_context, element_xpath, timeout=30):
    selenium_base_context.wait_for_element_visible(element_xpath, timeout=timeout)
    selenium_base_context.wait_for_element_clickable(element_xpath, timeout=timeout)
    selenium_base_context.click(element_xpath)


@shared_task
def download_report():
    with SB(
            **get_headless_options(), uc=True, test=True
    ) as sb:
        sb.open('https://www.amazon.com/ap/signin')
        sb.sleep(5)

        email_login_xpath = '//*[@id="ap_email"]'
        continue_button_xpath = '//*[@id="continue"]'
        password_login_xpath = '//*[@id="ap_password"]'
        sign_in_submit_button_xpath = '//*[@id="signInSubmit"]'

        wait_for_element_clickable_and_type(sb, email_login_xpath, 'your_email')
        wait_for_element_clickable_and_click(sb, continue_button_xpath)
        sb.sleep(5)
        # passkey dialog opened here 
        wait_for_element_clickable_and_type(sb, password_login_xpath, 'your_password')
        wait_for_element_clickable_and_click(sb, sign_in_submit_button_xpath)
        sb.sleep(5)
```
